# Generated by Django 5.2.7 on 2025-11-11 06:26

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemedyAZPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Remedy A-Z Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='RemedyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Remedy Category',
                'verbose_name_plural': 'Remedy Categories',
            },
        ),
        migrations.CreateModel(
            name='RemedyIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Remedy Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='RemedyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('remedy_type', models.CharField(choices=[('homeopathic', 'Homeopathic'), ('ayurvedic', 'Ayurvedic'), ('herbal', 'Herbal')], max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Remedy Type',
                'verbose_name_plural': 'Remedy Types',
            },
        ),
        migrations.CreateModel(
            name='RemedyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('subtitle_hi', models.CharField(blank=True, max_length=255, verbose_name='Subtitle (Hindi)')),
                ('also_known_as', models.CharField(blank=True, help_text='Alternative names', max_length=255)),
                ('also_known_as_hi', models.CharField(blank=True, max_length=255, verbose_name='Also Known As (Hindi)')),
                ('overview', wagtail.fields.RichTextField(help_text='General overview of the remedy')),
                ('overview_hi', wagtail.fields.RichTextField(blank=True, verbose_name='Overview (Hindi)')),
                ('uses', wagtail.fields.RichTextField(help_text='What conditions this remedy treats')),
                ('uses_hi', wagtail.fields.RichTextField(blank=True, verbose_name='Uses (Hindi)')),
                ('dosage', wagtail.fields.RichTextField(help_text='How to use and dosage information')),
                ('dosage_hi', wagtail.fields.RichTextField(blank=True, verbose_name='Dosage (Hindi)')),
                ('preparation', wagtail.fields.RichTextField(blank=True, help_text='How the remedy is prepared')),
                ('preparation_hi', wagtail.fields.RichTextField(blank=True, verbose_name='Preparation (Hindi)')),
                ('benefits', wagtail.fields.RichTextField(help_text='Health benefits')),
                ('benefits_hi', wagtail.fields.RichTextField(blank=True, verbose_name='Benefits (Hindi)')),
                ('side_effects', wagtail.fields.RichTextField(blank=True, help_text='Possible side effects or precautions')),
                ('side_effects_hi', wagtail.fields.RichTextField(blank=True, verbose_name='Side Effects (Hindi)')),
                ('precautions', wagtail.fields.RichTextField(blank=True, help_text='Warnings and precautions')),
                ('precautions_hi', wagtail.fields.RichTextField(blank=True, verbose_name='Precautions (Hindi)')),
                ('interactions', wagtail.fields.RichTextField(blank=True, help_text='Interactions with other medicines')),
                ('interactions_hi', wagtail.fields.RichTextField(blank=True, verbose_name='Interactions (Hindi)')),
                ('ingredients', models.TextField(blank=True, help_text='Main ingredients')),
                ('potency', models.CharField(blank=True, help_text='For homeopathic remedies (e.g., 30C, 200C)', max_length=100)),
                ('dosha_effect', models.CharField(blank=True, help_text='For Ayurvedic: Effect on Vata, Pitta, Kapha', max_length=255)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(blank=True, related_name='remedies', to='remedies.remedycategory')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('remedy_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remedies', to='remedies.remedytype')),
            ],
            options={
                'verbose_name': 'Remedy Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
