# Generated by Django 5.2.7 on 2025-11-11 07:42

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remedies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remedypage',
            name='also_known_as_hi',
        ),
        migrations.RemoveField(
            model_name='remedypage',
            name='benefits_hi',
        ),
        migrations.RemoveField(
            model_name='remedypage',
            name='dosage_hi',
        ),
        migrations.RemoveField(
            model_name='remedypage',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='remedypage',
            name='interactions',
        ),
        migrations.RemoveField(
            model_name='remedypage',
            name='interactions_hi',
        ),
        migrations.RemoveField(
            model_name='remedypage',
            name='overview_hi',
        ),
        migrations.RemoveField(
            model_name='remedypage',
            name='precautions_hi',
        ),
        migrations.RemoveField(
            model_name='remedypage',
            name='preparation',
        ),
        migrations.RemoveField(
            model_name='remedypage',
            name='preparation_hi',
        ),
        migrations.RemoveField(
            model_name='remedypage',
            name='side_effects_hi',
        ),
        migrations.RemoveField(
            model_name='remedypage',
            name='subtitle_hi',
        ),
        migrations.RemoveField(
            model_name='remedypage',
            name='uses_hi',
        ),
        migrations.RemoveField(
            model_name='remedytype',
            name='remedy_type',
        ),
        migrations.AlterField(
            model_name='remedycategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='remedycategory',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='remedypage',
            name='also_known_as',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='remedypage',
            name='benefits',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='remedypage',
            name='dosage',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='remedypage',
            name='dosha_effect',
            field=models.CharField(blank=True, help_text='Effect on Vata, Pitta, Kapha', max_length=255),
        ),
        migrations.AlterField(
            model_name='remedypage',
            name='ingredients',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='remedypage',
            name='overview',
            field=wagtail.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='remedypage',
            name='potency',
            field=models.CharField(blank=True, help_text='e.g., 30C, 200C', max_length=100),
        ),
        migrations.AlterField(
            model_name='remedypage',
            name='precautions',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='remedypage',
            name='side_effects',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='remedypage',
            name='uses',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='remedytype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='remedytype',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='RemedyAZPage',
        ),
    ]
