# Generated by Django 5.2.7 on 2025-10-12 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_articlepage_slug_hi'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='author_image',
            field=models.ForeignKey(blank=True, help_text='Author profile photo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='author_slug',
            field=models.SlugField(blank=True, help_text='Author profile slug', max_length=255),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='medical_reviewer',
            field=models.CharField(blank=True, help_text='Medical reviewer name', max_length=255),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='reading_time',
            field=models.IntegerField(default=5, help_text='Estimated reading time in minutes'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='reviewer_credentials',
            field=models.CharField(blank=True, help_text='e.g., MD, DO, PhD', max_length=100),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='reviewer_image',
            field=models.ForeignKey(blank=True, help_text='Reviewer profile photo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='reviewer_slug',
            field=models.SlugField(blank=True, help_text='Reviewer profile slug', max_length=255),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='author',
            field=models.CharField(blank=True, help_text='Article author name', max_length=255),
        ),
    ]
