# Generated by Django 5.2.7 on 2025-10-12 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_articlepage_author_image_articlepage_author_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='author_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.articleauthor'),
        ),
    ]
