# Generated by Django 5.2.5 on 2025-11-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_articlepage_author_obj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='author_obj',
        ),
    ]
